version: '3'

# https://www.digitalocean.com/community/tutorials/how-to-install-wordpress-with-docker-compose
# http://www.cantoni.org/2019/10/25/wordpress-github-docker

services:
  db:
    image: mariadb:10.7.1
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    ports:
      - "3306:3306"
    volumes:
      - wordpress-dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

  wordpress:
      depends_on:
        - db
      image: wordpress:5.8.2-fpm-alpine
      container_name: wordpress
      restart: unless-stopped
      env_file: .env
      environment:
        - WORDPRESS_DB_HOST=db:3306
        - WORDPRESS_DB_USER=$MYSQL_USER
        - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
        - WORDPRESS_DB_NAME=wordpress
      volumes:
        - wordpress:/var/www/html
      networks:
        - app-network

  webserver:
      depends_on:
        - wordpress
      image: nginx:1.21.4-alpine
      container_name: webserver
      restart: unless-stopped
      ports:
        - "80:80"
      volumes:
        - wordpress:/var/www/html
        - ./nginx-conf:/etc/nginx/conf.d
        # - certbot-etc:/etc/letsencrypt
      networks:
        - app-network

volumes:
  certbot-etc:
  wordpress:
  wordpress-dbdata:

networks:
  app-network:
    driver: bridge
